# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# See https://www.packer.io/docs/templates/hcl_templates/blocks/packer for more info
packer {
  required_plugins {
    vagrant = {
      source  = "github.com/hashicorp/vagrant"
      version = "~> 1"
    }
  }
}

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "guest_additions" {
  type    = string
  default = "disable"
}

variable "vm_description" {
  type    = string
  default = "CentOS Stream 8 by KodeKloud.com"
}

variable "vm_version" {
  type    = string
  default = "CentOS Stream 8"
}

variable "iso_name" {
  type    = string
  default = "CentOS-Stream-8-20230710.0-x86_64-boot.iso"
}

variable "iso_path" {
  type    = string
  default = "./sw/centos"
}

variable "iso_checksum" {
  type    = string
  default = "sha256:029ead89f720becd5ee2a8cf9935aad12fda7494d61674710174b4674b357530"
}

variable "iso_url" {
  type    = string
  default = "http://mirrors.vinters.com/centos/8-stream/isos/x86_64/CentOS-Stream-8-20230710.0-x86_64-boot.iso"
}

variable "kickstart" {
  type    = string
  default = "https://raw.githubusercontent.com/albal/hcp-centos-8/main/http/kickstart.cfg"
}

variable "proxy" {
  type    = string
  default = "${env("http_proxy")}"
}

variable "box_name" {
  type    = string
  default = "Centos8"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "virtualbox-iso" "autogenerated_1" {
  boot_command            = ["<tab> text ks=${var.kickstart}<enter>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>"]
  boot_wait               = "10s"
  disk_size               = 32768
  guest_additions_mode    = "${var.guest_additions}"
  guest_additions_path    = "VBoxGuestAdditions_{{ .Version }}.iso"
  guest_os_type           = "RedHat_64"
  hard_drive_interface    = "sata"
  headless                = false
  http_directory          = "http"
  iso_checksum            = "${var.iso_checksum}"
  iso_urls                = ["${var.iso_path}/${var.iso_name}", "${var.iso_url}"]
  shutdown_command        = "echo 'vagrant'| sudo -S /sbin/poweroff"
  ssh_password            = "vagrant"
  ssh_port                = 22
  ssh_timeout             = "30m"
  ssh_username            = "vagrant"
  vm_name                 = "${var.box_name}"
  vboxmanage              = [["modifyvm", "{{ .Name }}", "--memory", "2048"], ["modifyvm", "{{ .Name }}", "--cpus", "2"], ["modifyvm", "{{ .Name }}", "--vram", "128"], ["modifyvm", "{{ .Name }}", "--graphicscontroller", "vmsvga"]]
  virtualbox_version_file = ".vbox_version"
  export_opts = [
        "--manifest",
        "--vsys", "0",
        "--description", "${var.vm_description}",
        "--version", "${var.vm_version}"
  ]
  format = "ova"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  description = "Build base CentOS 8 x86_64"

  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    environment_vars = ["http_proxy=${var.proxy}", "guest_additions_mode=${var.guest_additions}"]
    scripts          = ["scripts/01sshd.sh", "scripts/02vagrant.sh", "scripts/90virtualbox.sh", "scripts/98cleanup.sh", "scripts/99minimize.sh"]
  }

  post-processor "vagrant" {
    output               = "${var.box_name}.box"
    vagrantfile_template = "Vagrantfile"
    keep_input_artifact  = true
  }
  post-processor "artifice" {
    files = [ "output-autogenerated_1/*.ova" ]
  }
}
